Create a hybrid model for stock price/performance prediction using
numerical analysis of historical stock prices, and sentimental analysis
of news headlines

In [1]:
import pandas as pd
import warnings
warnings.simplefilter("ignore")
#data visvulization
import plotly.express as px
from scipy import stats
import matplotlib.pyplot as plt
import numpy as np
import plotly.figure_factory as ff
import plotly.graph_objects as go

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data1 = pd.read_csv('datast.csv')

In [4]:
dat = pd.concat([data,data1], axis=1)

In [5]:
dat

publish_date                                      headline_text  \
0                2001  win over cena satisfying but defeating underta...   
1                2001  Status quo will not be disturbed at Ayodhya; s...   
2                2001                Fissures in Hurriyat over Pak visit   
3                2001              America's unwanted heading for India?   
4                2001                 For bigwigs; it is destination Goa   
...               ...                                                ...   
3297167          2020      why tiktok removed 1 65 crore videos in india   
3297168          2020  apurva asrani calls alia bhatts mother soni ra...   
3297169          2020  kangana ranaut gets a doll version of herself ...   
3297170          2020  meezaan jaffrey reminisces his childhood days ...   
3297171          2020  prabhas20 titled as radhe shyam prabhas and po...   

              category    Result        Date         Open         High  \
0               sports  positive  2000-04-03  5070.500000  5085.000000   
1              unknown   neutral  2000-04-04  4907.410156  4907.410156   
2              unknown   neutral  2000-04-05  4616.359863  4852.450195   
3              unknown   neutral  2000-04-06  4899.450195  4899.450195   
4              unknown   neutral  2000-04-07  4987.100098  5222.799805   
...                ...       ...         ...          ...          ...   
3297167   gadgets-news   neutral         NaN          NaN          NaN   
3297168  entertainment   neutral         NaN          NaN          NaN   
3297169  entertainment  positive         NaN          NaN          NaN   
3297170  entertainment  positive         NaN          NaN          NaN   
3297171  entertainment  positive         NaN          NaN          NaN   

                 Low        Close    Adj Close  Volume  
0        4977.209961  5052.939941  5052.939941     0.0  
1        4666.950195  4691.459961  4691.459961     0.0  
2        4601.580078  4757.060059  4757.060059     0.0  
3        4608.109863  4866.729980  4866.729980     0.0  
4        4987.100098  5219.200195  5219.200195     0.0  
...              ...          ...          ...     ...  
3297167          NaN          NaN          NaN     NaN  
3297168          NaN          NaN          NaN     NaN  
3297169          NaN          NaN          NaN     NaN  
3297170          NaN          NaN          NaN     NaN  
3297171          NaN          NaN          NaN     NaN  

[3297172 rows x 11 columns]

In [6]:
df = dat.copy()

In [7]:
df.isnull().sum()

publish_date           0
headline_text          0
category               0
Result                 0
Date             3292040
Open             3292040
High             3292040
Low              3292040
Close            3292040
Adj Close        3292040
Volume           3292040
dtype: int64

In [8]:
df.drop('Date', axis = 1, inplace = True)

In [9]:
df.drop('headline_text', axis = 1, inplace = True)

In [10]:
df.drop('category', axis = 1, inplace = True)

In [11]:
df.head()

publish_date    Result         Open         High          Low        Close  \
0          2001  positive  5070.500000  5085.000000  4977.209961  5052.939941   
1          2001   neutral  4907.410156  4907.410156  4666.950195  4691.459961   
2          2001   neutral  4616.359863  4852.450195  4601.580078  4757.060059   
3          2001   neutral  4899.450195  4899.450195  4608.109863  4866.729980   
4          2001   neutral  4987.100098  5222.799805  4987.100098  5219.200195   

     Adj Close  Volume  
0  5052.939941     0.0  
1  4691.459961     0.0  
2  4757.060059     0.0  
3  4866.729980     0.0  
4  5219.200195     0.0

In [12]:
df.isnull().sum()

publish_date          0
Result                0
Open            3292040
High            3292040
Low             3292040
Close           3292040
Adj Close       3292040
Volume          3292040
dtype: int64

In [13]:
df['Open'] = df['Open'].fillna(df['Open'].mean())

In [14]:
df['Close'] = df['Close'].fillna(df['Close'].mean())

In [15]:
df['High'] = df['High'].fillna(df['High'].mean())

In [16]:
df['Low'] = df['Low'].fillna(df['Low'].mean())

In [17]:
df['Volume'] = df['Volume'].fillna(df['Volume'].mean())

In [18]:
df['Adj Close'] = df['Adj Close'].fillna(df['Adj Close'].mean())

In [19]:
df.isnull().sum()

publish_date    0
Result          0
Open            0
High            0
Low             0
Close           0
Adj Close       0
Volume          0
dtype: int64

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [21]:
df['Result'] = pd.DataFrame(le.fit_transform(df['Result']))
df

publish_date  Result          Open          High           Low  \
0                2001       2   5070.500000   5085.000000   4977.209961   
1                2001       1   4907.410156   4907.410156   4666.950195   
2                2001       1   4616.359863   4852.450195   4601.580078   
3                2001       1   4899.450195   4899.450195   4608.109863   
4                2001       1   4987.100098   5222.799805   4987.100098   
...               ...     ...           ...           ...           ...   
3297167          2020       1  17791.545972  17900.032539  17648.447422   
3297168          2020       1  17791.545972  17900.032539  17648.447422   
3297169          2020       2  17791.545972  17900.032539  17648.447422   
3297170          2020       2  17791.545972  17900.032539  17648.447422   
3297171          2020       2  17791.545972  17900.032539  17648.447422   

                Close     Adj Close        Volume  
0         5052.939941   5052.939941      0.000000  
1         4691.459961   4691.459961      0.000000  
2         4757.060059   4757.060059      0.000000  
3         4866.729980   4866.729980      0.000000  
4         5219.200195   5219.200195      0.000000  
...               ...           ...           ...  
3297167  17771.220723  17771.220723  77998.910675  
3297168  17771.220723  17771.220723  77998.910675  
3297169  17771.220723  17771.220723  77998.910675  
3297170  17771.220723  17771.220723  77998.910675  
3297171  17771.220723  17771.220723  77998.910675  

[3297172 rows x 8 columns]

In [22]:
dt  = [ 'Open',  'High', 'Low','Volume','Result']

In [23]:

dataa = df[dt]
dataa.reset_index(inplace = True)

In [24]:
dataa

index          Open          High           Low        Volume  \
0              0   5070.500000   5085.000000   4977.209961      0.000000   
1              1   4907.410156   4907.410156   4666.950195      0.000000   
2              2   4616.359863   4852.450195   4601.580078      0.000000   
3              3   4899.450195   4899.450195   4608.109863      0.000000   
4              4   4987.100098   5222.799805   4987.100098      0.000000   
...          ...           ...           ...           ...           ...   
3297167  3297167  17791.545972  17900.032539  17648.447422  77998.910675   
3297168  3297168  17791.545972  17900.032539  17648.447422  77998.910675   
3297169  3297169  17791.545972  17900.032539  17648.447422  77998.910675   
3297170  3297170  17791.545972  17900.032539  17648.447422  77998.910675   
3297171  3297171  17791.545972  17900.032539  17648.447422  77998.910675   

         Result  
0             2  
1             1  
2             1  
3             1  
4             1  
...         ...  
3297167       1  
3297168       1  
3297169       2  
3297170       2  
3297171       2  

[3297172 rows x 6 columns]

In [25]:
dataa.drop('index', axis = 1, inplace = True)

In [26]:
dataa

Open          High           Low        Volume  Result
0         5070.500000   5085.000000   4977.209961      0.000000       2
1         4907.410156   4907.410156   4666.950195      0.000000       1
2         4616.359863   4852.450195   4601.580078      0.000000       1
3         4899.450195   4899.450195   4608.109863      0.000000       1
4         4987.100098   5222.799805   4987.100098      0.000000       1
...               ...           ...           ...           ...     ...
3297167  17791.545972  17900.032539  17648.447422  77998.910675       1
3297168  17791.545972  17900.032539  17648.447422  77998.910675       1
3297169  17791.545972  17900.032539  17648.447422  77998.910675       2
3297170  17791.545972  17900.032539  17648.447422  77998.910675       2
3297171  17791.545972  17900.032539  17648.447422  77998.910675       2

[3297172 rows x 5 columns]

In [27]:
dataa.describe()

Open          High           Low        Volume        Result
count  3.297172e+06  3.297172e+06  3.297172e+06  3.297172e+06  3.297172e+06
mean   1.779155e+04  1.790003e+04  1.764845e+04  7.799891e+04  1.060411e+00
std    4.347050e+02  4.362195e+02  4.320520e+02  4.121799e+04  5.461668e-01
min    2.621890e+03  2.682590e+03  2.594870e+03  0.000000e+00  0.000000e+00
25%    1.779155e+04  1.790003e+04  1.764845e+04  7.799891e+04  1.000000e+00
50%    1.779155e+04  1.790003e+04  1.764845e+04  7.799891e+04  1.000000e+00
75%    1.779155e+04  1.790003e+04  1.764845e+04  7.799891e+04  1.000000e+00
max    4.226300e+04  4.227387e+04  4.185029e+04  3.181510e+07  2.000000e+00

In [28]:
X =  dataa.drop('Result', axis =1)
X= dataa.iloc[:,0:4].values
X

array([[ 5070.5       ,  5085.        ,  4977.209961  ,     0.        ],
       [ 4907.410156  ,  4907.410156  ,  4666.950195  ,     0.        ],
       [ 4616.359863  ,  4852.450195  ,  4601.580078  ,     0.        ],
       ...,
       [17791.54597174, 17900.03253854, 17648.44742168, 77998.91067538],
       [17791.54597174, 17900.03253854, 17648.44742168, 77998.91067538],
       [17791.54597174, 17900.03253854, 17648.44742168, 77998.91067538]])

In [29]:
y = dataa.iloc[:,-1].values
y


array([2, 1, 1, ..., 2, 2, 2])

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test= train_test_split(X,y,random_state = 0 , test_size = 0.33)

In [32]:
X_train.shape,y_train.shape

((2209105, 4), (2209105,))

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(X_train,y_train)

array([[ 3.57169378e-05,  4.24173542e-05,  3.93484156e-05,
        -2.08632971e-04],
       [ 3.57169378e-05,  4.24173542e-05,  3.93484156e-05,
        -2.08632971e-04],
       [ 3.57169378e-05,  4.24173542e-05,  3.93484156e-05,
        -2.08632971e-04],
       ...,
       [ 3.57169378e-05,  4.24173542e-05,  3.93484156e-05,
        -2.08632971e-04],
       [ 3.57169378e-05,  4.24173542e-05,  3.93484156e-05,
        -2.08632971e-04],
       [ 3.57169378e-05,  4.24173542e-05,  3.93484156e-05,
        -2.08632971e-04]])

In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import tree

In [35]:
dt =  DecisionTreeClassifier()

In [36]:
model = dt.fit(X_train,y_train)

In [37]:
model_Score = model.score(X_test,y_test)
y_pred = model.predict(X_test)
print(model_Score)

0.6972980524177279


In [38]:
from sklearn.linear_model import LogisticRegression

In [39]:
lr =  LogisticRegression()


In [40]:
m1 = lr.fit(X_train,y_train)

In [41]:
m1_score = m1.score(X_test,y_test)
y_pre = m1.predict(X_test)


In [42]:
m1_score

0.6975498751455563

In [43]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

After Creating The Hybrid_Model I an say that while using LogisticRegression acurracy_score a point better than Decision Tree